name: frc_scouting_app
description: 'A mobile app developed by members of FIRST Robotics team 3464 "Sim-City"'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/clipboard.png
    - assets/images/clipboardbottombar.png
    - assets/images/statsbottombar.png
    - assets/images/userbottombar.png
    - assets/images/teambottombar.png

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SF-Pro-Black.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        # Italic versions
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic